/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import Connection.ConnectionQLTV;
import controler.QLTK_Controller;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Model_TaiKhoan;
import notification.Notification;
import notification.Notification.Type;
import notification.Notification.Location;
import org.json.JSONException;
import swing.button;
import javax.swing.table.TableModel;

/**
 *
 * @author Think Pad
 */
public class Form_QLTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form From_QLTaiKhoan
     */
    public static List<Model_TaiKhoan> arrTK = new ArrayList<>();
    public static String taikhoan,matkhau,MaNV;
    public static boolean ktThem;
    public static String macu;
    private int x;
     String[] columnNamesTaiKhoan = {"Tài Khoản", "Mật Khảu", "Mã Nhân Viên"};
    DefaultTableModel tblDanhSach = new DefaultTableModel(columnNamesTaiKhoan, 0);
    
    public void KhoaMo(boolean b) {
        btThemTK.setEnabled(b);
        btSuaTK.setEnabled(b);
        btXoa.setEnabled(b);

        btLuu.setEnabled(!b);
        btThemTK.setStyle(button.ButtonStyle.PRIMARY);
        btSuaTK.setStyle(button.ButtonStyle.PRIMARY);
        btXoa.setStyle(button.ButtonStyle.PRIMARY);

        btLuu.setStyle(button.ButtonStyle.SECONDARY);

    }
    // Khi ấn vào nút thêm đổi màu các button khác

    public void ColorButtonAdd() {
        btThemTK.setStyle(button.ButtonStyle.SECONDARY);
        btSuaTK.setStyle(button.ButtonStyle.SECONDARY);
        btXoa.setStyle(button.ButtonStyle.SECONDARY);
        btReload.setStyle(button.ButtonStyle.DESTRUCTIVE);
        btLuu.setStyle(button.ButtonStyle.DESTRUCTIVE);

    }// Khi ấn vào button reload đổi màu các button khác

    public void ColorButtonReload() {
        btThemTK.setStyle(button.ButtonStyle.PRIMARY);
        btSuaTK.setStyle(button.ButtonStyle.PRIMARY);
        btXoa.setStyle(button.ButtonStyle.PRIMARY);

    }
    public Form_QLTaiKhoan() throws JSONException, IOException {
        initComponents();
        tblDanhSach = (DefaultTableModel) tbTaiKhoan.getModel();
        LayNguon();
        KhoaMo(true);

    }

    public void XoaTrang() {
        txtTaiKhoan.setText("");
        txtMatKhau.setText("");
        txtMaNhanVien.setText("");
    }
    public void LayNguon() throws JSONException, IOException {

        try {
            arrTK = QLTK_Controller.LayNguonTK("");
           

        } catch (SQLException ex) {
            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblDanhSach.setRowCount(0); // Xóa trắng
        arrTK.forEach(p -> {
            tblDanhSach.addRow(new Object[]{
                p.getTaiKhoan(), p.getMatKhau(), p.getMaNV()

            });
        });

    }
//    public Form_QLTaiKhoan() throws SQLException {
//        initComponents();
//        getData(tbTaiKhoan, "1");
//        tbTaiKhoan.addMouseListener(new MouseListener() {
//            @Override
//            public void mouseClicked(MouseEvent e) {
//                int r = tbTaiKhoan.getSelectedRow();
//                if (r != -1) {
//                    txtTaiKhoan.setText(tbTaiKhoan.getValueAt(r, 0).toString());
//                    txtMatKhau.setText(tbTaiKhoan.getValueAt(r, 1).toString());
//                    txtMaNhanVien.setText(tbTaiKhoan.getValueAt(r, 2).toString());
//
//                }
//            }
//
//            @Override
//            public void mousePressed(MouseEvent e) {
//            }
//
//            @Override
//            public void mouseReleased(MouseEvent e) {
//            }
//
//            @Override
//            public void mouseEntered(MouseEvent e) {
//            }
//
//            @Override
//            public void mouseExited(MouseEvent e) {
//            }
//
//        });
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbTaiKhoan = new swing.Table();
        lbTaiKhoan = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lbMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        lbMaNhanVien = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btThemTK = new swing.button();
        btSuaTK = new swing.button();
        btXoa = new swing.button();
        btReload = new swing.button();
        btLuu = new swing.button();

        setBackground(new java.awt.Color(255, 255, 255));

        tbTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tài Khoản", "Mật Khẩu", "Mã Nhận Viên"
            }
        ));
        tbTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTaiKhoan);

        lbTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTaiKhoan.setText("Tên tài khoản");

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtTaiKhoan.setBorder(null);

        lbMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMatKhau.setText("Mật Khẩu");

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMatKhau.setBorder(null);

        lbMaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMaNhanVien.setText("Mã nhân viên");

        txtMaNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaNhanVien.setBorder(null);

        btThemTK.setText("Thêm");
        btThemTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemTKActionPerformed(evt);
            }
        });

        btSuaTK.setText("Sửa");
        btSuaTK.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btSuaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaTKActionPerformed(evt);
            }
        });

        btXoa.setText("Xóa");
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btReload.setBackground(new java.awt.Color(255, 255, 255));
        btReload.setText("Reload");
        btReload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btReload.setStyle(swing.button.ButtonStyle.DESTRUCTIVE);
        btReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReloadActionPerformed(evt);
            }
        });

        btLuu.setText("Lưu");
        btLuu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMatKhau)
                    .addComponent(lbTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTaiKhoan)
                    .addComponent(txtMatKhau)
                    .addComponent(txtMaNhanVien)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(503, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btReload, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMaNhanVien)
                .addGap(18, 18, 18)
                .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btReload, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSuaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemTKActionPerformed
        ktThem = true;
        KhoaMo(false);
        txtTaiKhoan.requestFocus();
        ColorButtonAdd();
    }//GEN-LAST:event_btThemTKActionPerformed

    private void btSuaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaTKActionPerformed
        if (txtTaiKhoan.getText().length() <= 0) {
            return;
        }
        macu = txtTaiKhoan.getText();
        ktThem = false;
        KhoaMo(false);
        txtTaiKhoan.requestFocus();
        ColorButtonAdd();
    }//GEN-LAST:event_btSuaTKActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        if (txtTaiKhoan.getText().length() <= 0) {
            return;
        }
        int kq = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa tài khoản không[" + txtTaiKhoan.getText() + "]",
                "Thông báo ", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (kq == JOptionPane.YES_NO_OPTION) {
            macu = txtTaiKhoan.getText();
            QLTK_Controller.Delete(macu);
            XoaTrang();
            try {
                LayNguon();
            } catch (JSONException ex) {
                Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReloadActionPerformed
        XoaTrang();
        try {
            LayNguon();
        } catch (JSONException ex) {
            Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        KhoaMo(true);
        ColorButtonReload();
    }//GEN-LAST:event_btReloadActionPerformed

    private void btLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuuActionPerformed
        if (txtTaiKhoan.getText().length() <= 0 || txtMatKhau.getText().length() <= 0 || txtMaNhanVien.getText().length() <= 0) {
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.INFO, Notification.Location.TOP_RIGHT, "Bạn chưa nhập đầy dử thông tin");
            panel.showNotification();
            txtTaiKhoan.requestFocus();
            return;
        }
        
        macu = txtTaiKhoan.getText();

        // thực hiện ghi
        taikhoan = txtTaiKhoan.getText();
        matkhau = txtMatKhau.getText();
        MaNV = txtMaNhanVien.getText();
        
        Model_TaiKhoan temp = new Model_TaiKhoan(taikhoan,matkhau,MaNV);
        if (ktThem == true) {
            try {
                if (QLTK_Controller.KiemTraTrungMa(txtTaiKhoan.getText(), ktThem, txtTaiKhoan.getText()) == true) {
                    Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Bạn nhập trùng tên Tài Khoản");
                    panel.showNotification();
                    txtTaiKhoan.requestFocus();
                    return;
                    
                }
            } catch (JSONException ex) {
                Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                QLTK_Controller.ThemMoi(temp);
            } catch (JSONException ex) {
                Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
            }
            Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.SUCCESS, Notification.Location.BOTTOM_RIGHT, "Thêm mới thành công");
            panel.showNotification();

        } else {
            if (ktThem == false) {

                try {
                    if (QLTK_Controller.KiemTraTrungMa(txtTaiKhoan.getText(), ktThem, txtTaiKhoan.getText()) == true) {
                        txtTaiKhoan.requestFocus();
                        try {
                            QLTK_Controller.CapNhat(temp);
                        } catch (JSONException ex) {
                            Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.SUCCESS, Notification.Location.BOTTOM_RIGHT, "Sửa  thành công");
                        panel.showNotification();
                        
                    } else {
                        Notification panel = new Notification((JFrame) SwingUtilities.getWindowAncestor(this), Notification.Type.WARNING, Notification.Location.BOTTOM_RIGHT, "Sửa  không thành công");
                        panel.showNotification();
                    }
                } catch (JSONException ex) {
                    Logger.getLogger(Form_QLTaiKhoan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        try {
            LayNguon();
        } catch (JSONException ex) {
            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Form_NhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        XoaTrang();
        KhoaMo(true);
        ColorButtonReload();
    }//GEN-LAST:event_btLuuActionPerformed

    private void tbTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTaiKhoanMouseClicked
        int index = tbTaiKhoan.getSelectedRow();
        TableModel model = tbTaiKhoan.getModel();
        taikhoan = model.getValueAt(index, 0).toString();
        matkhau = model.getValueAt(index, 1).toString();
        MaNV = model.getValueAt(index, 2).toString();
        
        txtTaiKhoan.setText(taikhoan);
        txtMaNhanVien.setText(MaNV);
        txtMatKhau.setText(matkhau);
        
      
    }//GEN-LAST:event_tbTaiKhoanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.button btLuu;
    private swing.button btReload;
    private swing.button btSuaTK;
    private swing.button btThemTK;
    private swing.button btXoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JLabel lbMatKhau;
    private javax.swing.JLabel lbTaiKhoan;
    private swing.Table tbTaiKhoan;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
